steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecofusion:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ecofusion:$COMMIT_SHA']

# Set up kustomize
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['kustomize', 'edit', 'set', 'image', 'gcr.io/$PROJECT_ID/ecofusion=gcr.io/$PROJECT_ID/ecofusion:$COMMIT_SHA']

# Deploy container image to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=.
  - --image=gcr.io/$PROJECT_ID/ecofusion:$COMMIT_SHA
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

images:
- 'gcr.io/$PROJECT_ID/ecofusion:$COMMIT_SHA'

substitutions:
  _CLOUDSDK_COMPUTE_ZONE: us-central1-c
  _CLOUDSDK_CONTAINER_CLUSTER: your-cluster-name