steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecofusion-website:$SHORT_SHA', '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecofusion-website:$SHORT_SHA']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=k8s/
    - --image=gcr.io/$PROJECT_ID/ecofusion-website:$SHORT_SHA
    - --location=us-central1-a
    - --cluster=ecofusion-cluster

images:
- 'gcr.io/$PROJECT_ID/ecofusion-website:$SHORT_SHA'