steps:
  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/project-ecofusion/my-website:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/project-ecofusion/my-website:$COMMIT_SHA']

  # Explicitly get GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'ecofusion-cluster'
      - '--zone=us-central1-a'
      - '--project=project-ecofusion'

  # Set kubectl context to the correct namespace
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'config'
      - 'set-context'
      - '--current'
      - '--namespace=ecofusion-website'

  # Update deployment image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/ecofusion-website-deployment'
      - 'ecofusion-website=gcr.io/project-ecofusion/my-website:$COMMIT_SHA'
      - '-n'
      - 'ecofusion-website'

  # Apply deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml', '-n', 'ecofusion-website']

  # Apply service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'service.yaml', '-n', 'ecofusion-website']

images:
  - 'gcr.io/project-ecofusion/my-website:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY