steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster-1'
      - '--region'
      - 'us-central1'
      - '--project'
      - 'portfolio-ghuman'
    env:
      - 'CLOUDSDK_GET_CREDENTIALS_OPTS=--internal-ip --quiet'
