steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:$SHORT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:$SHORT_SHA']

  # Update the deployment file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      sed -i 's|COMMIT_SHA|'$SHORT_SHA'|g' deployment.yaml

  # Deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=kubernetes/
    - --image=us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:$SHORT_SHA
    - --location=us-central1-c
    - --cluster=ecofusion-cluster

images:
  - 'us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY