steps:
  # Build the Docker image
  - name: 'gcrio/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcrio/ecofusion:$SHORT_SHA', '.']

  # Push the image to Artifact Registry
  - name: 'gcrio/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcrio/ecofusion:$SHORT_SHA']

  # Get GKE credentials
  - name: 'gcrio/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster-1'
      - '--zone'
      - 'us-central1-a'
      - '--project'
      - '$PROJECT_ID'

  # Update the deployment to use the new image
  - name: 'gcrio/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/ecofusion-deployment'
      - 'ecofusion-app=us-central1-docker.pkg.dev/$PROJECT_ID/gcrio/ecofusion:$SHORT_SHA'

  # Apply any changes to the deployment
  - name: 'gcrio/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']

  # Apply any changes to the service
  - name: 'gcrio/cloud-builders/kubectl'
    args: ['apply', '-f', 'service.yaml']

  # Force redeployment to clear pod-level cache
  - name: 'gcrio/cloud-builders/kubectl'
    args:
    - 'rollout'
    - 'restart'
    - 'deployment/ecofusion-deployment'

  # Wait for rollout to complete
  - name: 'gcrio/cloud-builders/kubectl'
    args:
    - 'rollout'
    - 'status'
    - 'deployment/ecofusion-deployment'
    - '--timeout=600s'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcrio/ecofusion:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY