steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-website:$SHORT_SHA'
      - '.'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/my-website:$SHORT_SHA'

  # Set up kubectl with the correct context
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecofusion-cluster'
    args:
    - 'config'
    - 'view'
    - '--raw'
    - '--minify'
    - '--flatten'
    - '--merge'
    id: 'kubectl-context'

  # Validate deployment manifest
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '--dry-run=client', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecofusion-cluster'
    waitFor: ['kubectl-context']

  # Apply the deployment manifest
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecofusion-cluster'
    waitFor: ['kubectl-context']

  # Validate service manifest
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '--dry-run=client', '-f', 'service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecofusion-cluster'
    waitFor: ['kubectl-context']

  # Apply the service manifest
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecofusion-cluster'
    waitFor: ['kubectl-context']

  # Update deployment to use the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/my-node-app'
    - 'my-node-app=gcr.io/$PROJECT_ID/my-website:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ecofusion-cluster'
    waitFor: ['kubectl-context']

images:
  - 'gcr.io/$PROJECT_ID/my-website:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY