steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:v1-${SHORT_SHA}'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:v1-${SHORT_SHA}'

  # Step 3: Get GKE credentials to interact with the cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-cluster-1'
      - '--region'
      - 'us-central1'
      - '--project'
      - 'portfolio-ghuman'
      - '--quiet'

  # Step 4: Update the Kubernetes deployment to use the new Docker image
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'KUBECTL_VERSION=1.30'
    args:
      - 'set'
      - 'image'
      - 'deployment/ecofusion-deployment'
      - 'ecofusion-app=us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:v1-${SHORT_SHA}'

  # Step 5: Rollout restart to ensure the new image is deployed
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'KUBECTL_VERSION=1.30'
    args:
      - 'rollout'
      - 'restart'
      - 'deployment/ecofusion-deployment'

  # Step 6: Wait for the rollout to complete, ensuring all pods are updated
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'KUBECTL_VERSION=1.30'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/ecofusion-deployment'
      - '--timeout=600s'

images:
  - 'us-central1-docker.pkg.dev/portfolio-ghuman/ecofusion-repo/ecofusion:v1-${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
