apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      serviceAccountName:  ecofusion-service-account-name # Add this line
      containers:
      - name: my-website
        image: us-central1-docker.pkg.dev/sample-product-catalog/my-website-repo/my-website:v2
        ports:
        - containerPort: 3000
