apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ecofusion-frontend-config
  namespace: ecofusion
spec:
  sslPolicy: ecofusion-ssl-policy
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT