apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecofusion-ingress
  namespace: ecofusion
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "34.72.220.198"
    networking.gke.io/managed-certificates: "ecofusion-managed-cert"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: "ecofusion-frontend-config"
spec:
  rules:
    - host: ghuamanportfolio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecofusion-service
                port: 
                  number: 80