apiVersion: v1
kind: Service
metadata:
  name: ecofusion-website-service
  namespace: ecofusion-website
spec:
  selector:
    app: ecofusion-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer