apiVersion: v1
kind: Service
metadata:
  name: ecofusion-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  # For GKE Autopilot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: ecofusion-app
