apiVersion: v1
kind: Service
metadata:
  name: ecofusion-service
  namespace: ecofusion
  annotations:
    networking.gke.io/load-balancer-ip: "34.170.52.5"
spec:
  selector:
    app: ecofusion-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer