apiVersion: v1
kind: Service
metadata:
  name: ecofusion-service
  namespace: ecofusion
spec:
  selector:
    app: ecofusion-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer